name 'ext_ec_handlers'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures ext_ec_handlers'
version '0.1.3'
chef_version '>= 12.14'
