Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu/xenial64"
  c.vm.hostname = "secondisk-ubuntu-xenial64.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-resourcetest-secondisk-ubuntu-xenial64"
    p.customize ["createhd", "--filename", "d:/VMs/disk2.vdi", "--size", 1024]
    p.customize ["storagectl", :id, "--name", "IDE", "--controller", "PIIX4", "--portcount", 2]
    p.customize ["storageattach", :id, "--storagectl", "IDE", "--port", 1, "--device", 1, "--type", "hdd", "--medium", "d:/VMs/disk2.vdi"]
  end
end
