Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "mwrock/Windows8.1-amd64"
  c.vm.hostname = "default-mwrock-Windows81-amd64.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-setupmyenv-default-mwrock-Windows81-amd64-f2302dec-f00a-4dc1-a170-739652ae6f12"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
