name 'cis_ubuntu'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures cis_ubuntu'
long_description 'Installs/Configures cis_ubuntu'
version '0.1.0'
chef_version '>= 14.0'
depends 'audit'
